{% set name = "afar" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/afar-{{ version }}.tar.gz
  sha256: 24a324adb54e6ebb74c7c9b5a7c8b126eed3492517a7079c0ce0b7feafa8b014

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - distributed >=2021.9.1
    - innerscope
    - python >=3.7

test:
  imports:
    - afar
    - afar.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eriknw/afar
  summary: Run code on a Dask cluster via a context manager or IPython magic
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/eriknw/afar

extra:
  recipe-maintainers:
    - eriknw
